### ISSUE TITLE
Clean-up MS Word in ORCID fields

### ISSUE THREAD

**Issue by mconlon17** [ufvivotech/ufDataQualityImprovement#529]
May have to drop all orcids for the user and recreate

Easy to find.  Use:

    SELECT ?uri ?orcid
    WHERE {
      ?uri vivo:orcidId ?orcid .
    }

**Comment by nrejack** [comment]
Clean-up completed on 10/28/2015. Clean-up performed using multiple methods:
1) manual delete and re-add from interface. When this was not possible due to VIVO errors...
2) generation of RDF via SPARQL CONSTRUCT, subtraction via Site Admin menu, and re-add of ORCID via interface.

Leading/trailing spaces also removed.
